"""add sub units logic for selling strips

Revision ID: 04451bdfd5a8
Revises: 54f705bde946
Create Date: 2026-06-05 16:58:41.375769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04451bdfd5a8'
down_revision: Union[str, Sequence[str], None] = '54f705bde946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_divisible', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('parts_per_unit', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('part_name', sa.String(), nullable=True))
    op.add_column('products', sa.Column('part_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'part_price')
    op.drop_column('products', 'part_name')
    op.drop_column('products', 'parts_per_unit')
    op.drop_column('products', 'is_divisible')
    # ### end Alembic commands ###
