"""add tax columns to purchase orders

Revision ID: 07b4ebaf8fb5
Revises: 99cee50612ea
Create Date: 2026-06-06 03:29:06.221314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b4ebaf8fb5'
down_revision: Union[str, Sequence[str], None] = '99cee50612ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('tax_percentage', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('purchase_orders', sa.Column('tax_value', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'tax_value')
    op.drop_column('purchase_orders', 'tax_percentage')
    # ### end Alembic commands ###
