"""add product batches and expiry tracking

Revision ID: 4a7ac2c55130
Revises: 4d68b65b3293
Create Date: 2026-06-06 00:14:11.240076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7ac2c55130'
down_revision: Union[str, Sequence[str], None] = '4d68b65b3293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_batches_batch_number'), 'product_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_product_batches_id'), 'product_batches', ['id'], unique=False)
    op.add_column('purchase_items', sa.Column('batch_number', sa.String(), nullable=True))
    op.add_column('purchase_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_items', 'expiry_date')
    op.drop_column('purchase_items', 'batch_number')
    op.drop_index(op.f('ix_product_batches_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_batch_number'), table_name='product_batches')
    op.drop_table('product_batches')
    # ### end Alembic commands ###
