"""refactor inventory to use base unit method with total_parts

Revision ID: e81656d8b4c8
Revises: 04451bdfd5a8
Create Date: 2026-06-05 17:19:18.564965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81656d8b4c8'
down_revision: Union[str, Sequence[str], None] = '04451bdfd5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_parts', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('products', 'total_parts')
    # ### end Alembic commands ###
