"""add status column to purchase_orders

Revision ID: ff090e216830
Revises: cea37b5e9845
Create Date: 2026-06-05 23:23:06.443711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff090e216830'
down_revision: Union[str, Sequence[str], None] = 'cea37b5e9845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('status', sa.String(), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'status')
    # ### end Alembic commands ###
